# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: ubuntu-latest
    services:
          mongodb:
              image: mongo
              env:
                MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_USERNAME}}
                MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_PASSWORD}}
                MONGO_INITDB_DATABASE: ${{secrets.DB_NAME}}
              options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                - 27017:27017

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      env:
        NODE_ENV: ${{secrets.NODE_ENV}}
        PORT: ${{secrets.PORT}}
        MONGO_URL: ${{secrets.MONGO_URL}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        MAX_WRONG_ATTEMPTS_BY_IP_PER_DAY: ${{secrets.MAX_WRONG_ATTEMPTS_BY_IP_PER_DAY}}
        MAX_CONSECUTIVE_FAILS_BY_EMAIL_AND_IP: ${{secrets.MAX_CONSECUTIVE_FAILS_BY_EMAIL_AND_IP}}
    - run: npm run build --if-present
    - run: npm test
